User.destroy_all
Club.destroy_all
UserClub.destroy_all
Episode.destroy_all
ClubEpisode.destroy_all

    User.create(username: "mrs161", password: "abc123", name: "Madeline Stalter", age: 25, favorite_genre: "Crime", profile_pic: Faker::LoremPixel.image)
    User.create(username: "mh87", password: "abc123", name: "Mahdi Hawary", age: 26, favorite_genre: "Fitness", profile_pic: Faker::LoremPixel.image)
    User.create(username: "pandabear", password: "abc123", name: "Sean Padden", age: 26, favorite_genre: "Spirituality", profile_pic: Faker::LoremPixel.image)
    User.create(username: "kittycat", password: "abc123", name: "Logan Stalter", age: 23, favorite_genre: "Cooking", profile_pic: Faker::LoremPixel.image)
    User.create(username: "eaf40", password: "abc123", name: "Erik Frost" , age: 25, favorite_genre: "Comedy", profile_pic: Faker::LoremPixel.image)


    Club.create(name:"My Dear Detective", genre: "True Crime", club_image: "https://images.app.goo.gl/1FdtgFBkYU17jZns6")
    Club.create(name:"Sage & Crystal", genre: "Spirituality", club_image: "https://img.rawpixel.com/s3fs-private/rawpixel_images/website_content/pf-s54-karolina-grabowska-kaboompics-9382.jpg?bg=transparent&con=3&cs=srgb&dpr=1&fm=jpg&ixlib=php-3.1.0&q=80&usm=15&vib=3&w=1300&s=181bc2baa7db24b9f3c1f18232f94b5f")
    Club.create(name:"Hangry", genre: "Cooking", club_image: "https://www.eatright.org/-/media/eatrightimages/food/planningandprep/cookingtipsandtrends/culinary-lingo-688005624.jpg")
    Club.create(name:"Fit Friends", genre: "Health & Wellness", club_image: "https://majorhifi.com/wp-content/uploads/action-athlete-resized.jpg")
    Club.create(name:"Historic Huddle", genre: "History", club_image: "https://www.whitman.edu/images/Academics/Body-Image/history.jpg")
    Club.create(name:"Wunderlust", genre: "Travel", club_image: "https://www.study2europe.com/StudyEurope/wp-content/uploads/2018/11/f_International-Tourism.jpg")
    Club.create(name:"Comedy Cellar", genre: "Comedy", club_image: "https://amtshows.com/wp-content/uploads/2014/05/stand-up-comedy-neon-sign.jpg")
    Club.create(name:"A House Divided", genre: "New & Politics", club_image: "https://media.beliefnet.com/~/media/photos-with-attribution/patriotic/politics-unhappy-fight-american-flag-donkey-elephant_credit-shutterstock%20(2).jpg?as=1&extension=webp")
    Club.create(name:"Jammin'", genre: "Music", club_image: "https://www.openmicuk.co.uk/wp-content/uploads/2019/05/What-is-a-jam-session.jpg")


#CRIME
Episode.create(name: "My Favorite Murder", episode_number: 233, episode_title: "Free Range Children", description: "Karen and Georgia cover the Zoot Suit Ruits and the 1976 Chowchilla bus kidnapping.", date: "7/30/2020", episode_url: 'https://open.spotify.com/episode/7mL3gYU4RHZAqRs58tP7hz')
Episode.create(name: "My Favorite Murder", episode_number: 194, episode_title: "The SpoOoky Halloween Hometown Special", description: "Karen and Georgia celebrate Halloween by reading your spooky stories.", date: "10/31/2019", episode_url: 'https://open.spotify.com/episode/5Qn4M43xB6MI9xg9HlLZo8')
Episode.create(name: "My Favorite Murder", episode_number: 146, episode_title: "Dawna's Skinny Lighter", description: "Karen and Georgia cover the case of Randy Mock and the Seattle Cyanide Poisonings", date: "11/8/2018", episode_url: 'https://open.spotify.com/episode/0BGexfC46CM2InttIdEQG7')
Episode.create(name: "Last Podcast on the Left", episode_number: 422, episode_title: "The 1971 Manson Family Western Surplus Shootout", description: "This week, we recount the bizzare schema byt he Manson family to save Charles Manson from Prison and the famous family shootout that ensued between the would-be rescue party and the Hawthrone police department.", date: "8/24/2020", episode_url: 'https://open.spotify.com/episode/5YLizlEeLfjFB0jIdiLQbv')
Episode.create(name: "Last Podcast on the Left", episode_number: 388, episode_title: "The Vampire Hunters of Highgate Cemetery", description: "Today we explore the story of two legendary vampire hunters named Sean Manchester and David Farrant who, back in the early seventies, engaged in a serious rivalry concerning a certain vampyre that stalked the rows of London Highgate Cemetery. Was it a spectre with psychic draining abilities or a flesh and blood creature of the night preying on the young girls of Highgate? Tune in to find out!", date: "10/26/2019", episode_url: 'https://open.spotify.com/episode/7Fczm2hDrNgvMZoMj1hJAR')
Episode.create(name: "Last Podcast on the Left", episode_number: 376, episode_title: "Joe Palczynski/The Bloody Benders", description: "On this relaxed fit episode, we talk about the Baltimore spree killer Joe Palczynski who held a family hostage for days, the saga of the Bloody Benders, and MORE.", date: "8/2/2019", episode_url: 'https://open.spotify.com/episode/05k4BEn8W01NNEp5k1Dd5F')
#SPIRITUALITY
Episode.create(name: "Highest Self Podcast", episode_number: 316, episode_title: "How To Be Spiritually Sassy with Sah D'Simone", description: "Spirituality doesn't have to be ultra serious! In this episode I sit down with one of my besties Sah D'Simone to discuss why you can be your bold, freak, weird self AND still be spiritual! We discuss his experience of letting go of his sassiness to fit into the spiritual mold and how he realized he lost his touch of who he is. We also talk about the Tantric vs the aesthetic path and key differences. We share how most spiritual teachers are CIS white men and the importance of diversity. ER sldo dive into how to fight imposter syndrome, avoid labeling and step into your unique magic!", date: "10/25/2020", episode_url: 'https://open.spotify.com/episode/6gyBLVVURNPSSuShn0oaUG')
Episode.create(name: "Highest Self Podcast", episode_number: 207, episode_title: "Human Design: Exploring How You Were Meant to Operate with Erin Claire", description: "Finding out I was a projector was a game-changer for me. Everything made sense - the way I channel ideas, how I can see the big picture, why I KNOW I get burnt out doing all the things and have to force myself to just focus on one thing at a time! In this episode, we explore the four Human Design Archetypes(Projector, Generator, Manifestor, and Reflector) and what that means for each of us! ", date: "7/16/2019", episode_url: 'https://open.spotify.com/episode/6rSNi1hNAdJfBFdrRWpFf3')
Episode.create(name: "Highest Self Podcast", episode_number: 190, episode_title: "Activating Your Light", description: "In this episode, we GO THERE. You may recognize Heather from her popular spiritual Instagram @activationvibration and in this episode we discuss her journey, her spiritual views, and so much more. She is most definitely a sister from antoher lifetime and I know you'll love her too!", date: "5/13/2019", episode_url: 'https://open.spotify.com/episode/29Emc0ZqDSEaYkLenDPzqh')
Episode.create(name: "Lightworkers Lounge", episode_number: 50, episode_title: "Put Your Spirituality Into Practice", description: "Cancel culture. Mob mentality in social media. In today's episode we talk abotu current collective energies, and the importance of placing spiritual leaders or influencers next to you, rather than in front of you on a pedestal. A lot of well known people are being exposed to their true character. which isn't the character we curated in our minds. How should we react?", date: "8/12/2020", episode_url: 'https://open.spotify.com/episode/0J65g4Ige9fUKuLm5z6lDX')
Episode.create(name: "Lightworkers Lounge", episode_number: 40, episode_title: "Astrology: It's More Than Just Your Sun Sign (ft. Debra Silverman)!", description: "Debra Silverman is part astrologer, part psychologist, part comedian and ALL REAL. Over the past 40 years of private practice, Debra has helped thousands of individuals achieve emotional health and wisdom based on their unique personality and the four elements: water, air, earth, and fire. Debra's mothering approach to understanding people has earned her international fame and admiration. Join us on today's new podcast episode as we talk about basic astrology and what it means if you're missing an element from your birthday chart.", date: "7/15/2020", episode_url: 'https://open.spotify.com/episode/4sOlz2ByXck1FjNEMuqYtX')
Episode.create(name: "Lightworkers Lounge", episode_number: 35, episode_title: "4 Stages of Spiritual Awakening", description: "... and what happens once you reach the 4th? In this episode, we dive into the 4 classic signs that you're going through a spiritual awakening Inspired by a post made by Dr. Nicole, the Holistic Psychology on Instagram, we go over stage 1 through 4 of the intimate, at times intense, process of coming home to your role as a Lightworker.", date: "7/1/2020", episode_url: 'https://open.spotify.com/episode/4ZbTEjI2hrdqtSrKULNSUd')
#COOKING
Episode.create(name: "Home Cooking", episode_number: 10, episode_title: "Old Bay Leaves, New Bae Arrives", description: "We’re back for a third batch of episodes! Samin and Hrishi help a listener who is over-encumbered by a number of cucumbers, and Chef Detective fills in the missing pieces from a family recipe for pull-apart bread.", date: "9/30/2020", episode_url: 'https://open.spotify.com/episode/1HRCHrNTYrQ9kjSGAUcdCg')
Episode.create(name: "Home Cooking", episode_number: 8, episode_title: "Gettin’ Jalapeño Business (with Rachel Khong)", description: "Samin and Hrishi brainstorm snack ideas for hiking, but sometimes wander off the trail, and author Rachel Khong (@rrrrrrrachelkhong) breaks down her quest to find the best way to cook rice—without a rice cooker.", date: "8/5/2020", episode_url: 'https://open.spotify.com/episode/5TGU1eiF1Yg1S6kdpwnNrz')
Episode.create(name: "Home Cooking", episode_number: 5, episode_title: "Guess What? Chicken Butt Is Delicious (with Yo-Yo Ma)", description: "We’re closing out our miniseries with happy bellies, full hearts, and international treasure Yo-Yo Ma (@YoYo_Ma). In this episode, we talk about comfort, memories, the act of cooking as an act of love, and the art of wrapping food inside other food.", date: "5/6/2020", episode_url: 'https://open.spotify.com/episode/5aPBJiAcT7QKIhv3VP7dYy')
Episode.create(name: "The Sporkful", episode_number: 10, episode_title: "The World Eats Here: Stories From The Queens Night Market", description: "This was supposed to be the Queens Night Market’s big summer... When the open-air market debuted in 2015, the crowds were massive. Founder John Wang selected food vendors who represented more than 90 countries. And he had one rule for them: no item could cost more than $5. That way the market would be accessible to nearly everyone, and big businesses would stay away. In 2019 the market set a new record for attendance, and finally started to turn a small profit. In 2020 they planned to release a cookbook. Instead, because of coronavirus, the market never opened. This week, to understand some of what we’ve lost to the pandemic, we share a vivid reminder of what we had.", date: "9/7/2020", episode_url: 'https://open.spotify.com/episode/2B3vqOGsdDiDbXaDQFnMic')
Episode.create(name: "The Sporkful", episode_number: 1, episode_title: "The REAL Sausage King of Chicago (Live from Chicago Pt. 1)", description: "Live on stage from Chicago! Hot Doug explains why he turned down millions and closed his famous sausage shop. Plus, filmmaker and food writer Kevin Pang talks about his documentary, For Grace, about Chef Curtis Duffy, one of the top chefs in the world. And Curtis joins us to discuss his journey to the top, and to reveal his favorite candy.", date: "8/2/2015", episode_url: 'https://open.spotify.com/episode/0zWFgPJwNBGRpK8jjEpmC6')
Episode.create(name: "The Sporkful", episode_number: 25, episode_title: "10 YEARS #2 | Aleppo Sandwich Pt 2 (Update)", description: "Three years later... A famous sandwich shop in Aleppo, Syria, played a key role in changing Shadi Martini’s life forever. Today on The Sporkful we hear the rest of Shadi’s story, and conclude our quest to find out what happened to the shop during the civil war in Syria.", date: "9/21/2020", episode_url: 'https://open.spotify.com/episode/6ctUwsBkE4meOOHC0sulNj')
#HEALTH & WELLNESS
Episode.create(name: "Ali on the Run", episode_number: 277, episode_title: "Ben Chan, Ultra Runner & Activist", description: "If you've ever run a race in New York City, you know Ben Chan. He's the leopard print short-shorts and cowboy hat guy, and he's a staple on the NYC running scene. On this episode, in addition to talking about his on-the-run fashion choices, Ben shares the story of how he found running at age 30, by way of donating a kidney to a friend in need. And Ben talks about his firsthand experiences with racism, many of which he's experienced recently, and on the run. Ben talks about being the son of immigrants and grandson of refugees, and offers his perspective on what it means to create safe spaces and escapes by way of running.", date: "9/3/2020", episode_url: 'https://open.spotify.com/episode/2GnwNqJ0pt4zndYkW9XS49')
Episode.create(name: "Ali on the Run", episode_number: 265, episode_title: "Catching Up with Chris Heuisler", description: "A lot has changed for Chris Heuisler since the last time he was on the Ali on the Run Show. He turned 40! He's no longer the Global RunWestin Concierge. And he got sober. On this episode, Chris — for the first time publicly — talks about his past with alcoholism, and his journey to sobriety (SO PROUD OF YOU, CHRIS).", date: "7/22/2020", episode_url: 'https://open.spotify.com/episode/7wURSTwaeNjzovzFVx6j02')
Episode.create(name: "Ali on the Run", episode_number: 198, episode_title: "Rachel Gersten, Therapist & Co-Founder of Viva Wellness", description: "Rachel Gersten is a New York City-based licensed therapist, and is the co-founder of Viva Wellness. On this episode — perfect for the new year! — she dishes out advice about dealing with burnout, anxiety, and what to do when you realize you have no idea what you want to do with the rest of your life. She also talks about her lifelong battle with chronic pain, and how running more than 150 races, including marathons, has actually helped her cope with the pain.", date: "1/9/2020", episode_url: 'https://open.spotify.com/episode/1LYWUmzumIkbmmswoYtqnR')
Episode.create(name: "Yoga Girl Daily", episode_number: 29, episode_title: "Improving Your Home to Improve Your Heart", description: "Is there something in your home that needs fixing and bugs you on a daily basis? You may not have fun during today’s self-care practice, but you will feel great after it’s done - we are going to fix the broken thing! Removing anything from your to-do list, no matter how tiny, is guaranteed to lower stress and improve your day.", date: "9/25/2020", episode_url: 'https://open.spotify.com/episode/7vazpIuJIt48edwomQYmhH')
Episode.create(name: "Yoga Girl Daily", episode_number: 28, episode_title: "Meditating Your Way Home", description: "Is it difficult to quiet your mind during your meditation practice? Here’s some news: that doesn’t mean you’re bad at meditating, it means you’re human! Meditation is a practice that allows us to accept what is. It is not about turning your mind off, but acknowledging the thoughts as they come, and then returning to the present moment. It is about becoming the watcher of your thinking mind and the subtle dance that exists between your surface-level thoughts and moments of true consciousness.", date: "9/23/2020", episode_url: 'https://open.spotify.com/episode/58E97vyh4161yeTuoiBT4G')
Episode.create(name: "Yoga Girl Daily", episode_number: 15, episode_title: "Finding Gratitude for the Simple Things", description: "Today’s gratitude practice may start as only a practice, but it has the potential to become a regular and automatic part of your day. We have many mundane moments in our lives, from taking a shower to washing the dishes to making the bed. Tune in to learn how to infuse gratitude and bring presence into those seemingly meaningless moments that we often take for granted.", date: "9/3/2020", episode_url: 'https://open.spotify.com/episode/5DMhywK9kJqzf27PebXn1f')
#HISTORY
Episode.create(name: "History Unplugged Podcast", episode_number: 110, episode_title: "How Hollywood First Depicted the Atomic Bomb and the Manhattan Project", description: "Soon after atomic bombs exploded over Hiroshima and Nagasaki in 1945, MGM set out to make a movie studio chief Louis B. Mayer called “the most important story” he would ever film: a big budget dramatization of the Manhattan Project and the invention and use of the revolutionary new weapon.Over at Paramount, Hal B. Wallis was ramping up his own film version. His screenwriter: the novelist Ayn Rand, who saw in physicist J. Robert Oppenheimer the model for a character she was sketching for Atlas Shrugged.Today’s guest is Greg Mitchell’s, author of “The Beginning or the End,” and we discuss the first efforts of American media and culture to process the Atomic Age. A movie that began as a cautionary tale inspired by atomic scientists aiming to warn the world against a nuclear arms race would be drained of all impact due to revisions and retakes ordered by President Truman and the military—for reasons of propaganda, politics, and petty human vanity (this was Hollywood, after all).", date: "7/21/2020", episode_url: 'https://open.spotify.com/episode/6laNwyzHo2cEGDZcGCjVyP')
Episode.create(name: "History Unplugged Podcast", episode_number: 59, episode_title: "Death From Above - How Paratroopers Evolved From a WW1 Pipe Dream To A Key Part of Combined-Arms Assault", description: "Paratroopers are about the most peculiar breed of human beings I have ever witnessed. They treat their service as if it were some kind of cult, plastering their emblem on almost everything they own, making themselves up to look like insane fanatics with haircuts to ungentlemanly lengths, worshiping their units almost as if they were a God, and making weird animal noises like a band of savages... [but] generally speaking, the United States Paratroopers I’ve come in contact with are the most professional soldiers and the finest men I have ever had the pleasure to meet.”This unattributed quote sums up the unique role that paratroopers have played in the wars of the 20th and 21st centuries. With the invention of the airplane, military strategists imaged troops clinging to the wings of Wright Bros. flyers and landing in enemy trenches. Such plans never came to fruition, but technical advances made it possible to drops thousands of soldiers with reasonable safety and accuracy. During WW2, Nazi Germany's paratroopers (Fallschirmjäger) had incredible success in Norway and the Netherlands and even rescued Benito Mussolini in a commando mission. Over 22,000 of them were dropped on Crete. Allied paratroopers famously landed in France on the eve of D-Day, making Operation Overlord a possibility.In this episode, we look at the origins of paratrooping, its function in war, and how it was part of the evolution of military strategy in the 20 century, in which different combat arms were integrated to achieve complementary effects.", date: "6/18/2020", episode_url: 'https://open.spotify.com/episode/3789eX1hDcIqGrhdIssIKT')
Episode.create(name: "History Unplugged Podcast", episode_number: 40, episode_title: "Discovering Your Grandfather Was Joseph Stalin's Bodyguard", description: "Delving into your family history can reveal many surprises, but for Russian-American author Alex Halberstadt, it meant learning about his grandfather's experience as Joseph Stalin's bodyguard.As the last living member of Stalin's security revenue, his grandfather, who lives in Ukraine, spoke of the fear of coming to work every day with the possibility you could be executed in a purge. Halberstad also revisits Lithuania, his Jewish mother’s home, to examine the legacy of the Holocaust and the pernicious anti-Semitism that remains largely unaccounted for. And he returns to his birthplace, Moscow, where his grandmother designed homespun couture for Soviet ministers’ wives, his mother consoled dissidents at a psychiatric hospital, and his father made a dangerous living by selling black-market American recordsHis book, Young Heroes of the Soviet Union, is an investigation into the fragile boundary between history and biography. As Halberstadt revisits the sites of his family’s formative traumas, he uncovers a multigenerational transmission of fear, suffering, and rage. And he comes to realize something more: Nations, like people, possess formative traumas that penetrate into the most private recesses of their citizens’ lives.", date: "4/30/2020", episode_url: 'https://open.spotify.com/episode/0YYoMVRqZBSguYLY0b3UpW')
Episode.create(name: "Stuff You Missed in History Class", episode_number: 147, episode_title: "Nina Otero-Warren", description: "Nina Otero-Warren was from a prominent New Mexico family, and worked in education, politics, and the suffrage movement, focusing largely on Spanish speakers.", date: "9/30/2020", episode_url: 'https://open.spotify.com/episode/6XYNuGwKywtjJGcjo04T9I')
Episode.create(name: "Stuff You Missed in History Class", episode_number: 145, episode_title: "James Forten", description: "As a child and young man, James was part of the British colonies that rebelled against rule from the throne. As an adult, he made his fortune in sail making, and turned his influence to the causes of abolition and civil rights.", date: "9/14/2020", episode_url: 'https://open.spotify.com/episode/3HkwjezotKpvdUNfa5FhIG')
Episode.create(name: "Stuff You Missed in History Class", episode_number: 140, episode_title: "Women’s War of 1929", description: "The Women’s War was a response to British colonialism in Nigeria. British authorities described the group as a “hostile mob” because they didn’t recognize that the so-called mob was largely a long-established method for Igbo women to hold men accountable.", date: "9/9/2020", episode_url: 'https://open.spotify.com/episode/7FpwYQlL5bStot4vHiv8ud')
#TRAVEL
Episode.create(name: "Amateur Traveler Travel Podcast", episode_number: 720, episode_title: "Driving the Carretera Austral, Chile", description: "Hear about travel driving the Carretera Austral in Chile as the Amateur Traveler talks to travel journalist and guidebook author Steph Dyson about a country she literally wrote the book on.", date: "9/5/2020", episode_url: 'https://open.spotify.com/episode/5hFeZQHrDefjmS7JQeX8xR')
Episode.create(name: "Amateur Traveler Travel Podcast", episode_number: 680, episode_title: "Travel to the Canary Islands", description: "Hear about travel to the Canary Islands as the Amateur Traveler talks to Alice Ford from alicesadventuresonearth.com about the best of the Canary Islands.", date: "11/12/2019", episode_url: 'https://open.spotify.com/episode/752YWOqjqE3A4zAP8NtRvG')
Episode.create(name: "Amateur Traveler Travel Podcast", episode_number: 699, episode_title: "Climbing Mount Kilimanjaro", description: "Hear about climbing Mount Kilimanjaro as the Amateur Traveler talks to Kylie Chenn from Acanela Expeditions about what you should know about climbing the tallest mountain in Africa.", date: "4/4/2020", episode_url: 'https://open.spotify.com/episode/56usKtD8zzsFXLqakUL0KI')
Episode.create(name: "Postcard Academy Travel Podcast", episode_number: 76, episode_title: "Artisan Florence: Insider Guide to the Best Local Shopping Experiences", description: "During the Renaissance, money flowed into Florence’s growing banking sector and the elite, including the Medici family, showed off their new wealth with art, palaces, and luxury goods. Lost in Florence is a beautiful book that highlights the best of independent Florence, from food and wine, to hotels and shopping. As the Postcard Academy podcast has covered food and wine on previous episodes, I dedicated my conversation with Nardia, an Australian expat who spent years in Florence before moving to Bangkok, on Florence’s artisans. Learn where to find the best jewelry, clothes, perfume, stationery and more.", date: "6/24/2019", episode_url: 'https://open.spotify.com/episode/2m2Dx7xxOZV7qpdGN82iRN')
Episode.create(name: "Postcard Academy Travel Podcast", episode_number: 70, episode_title: "Roadtrip! Part 1: Croatia's Dalmatian Coast", description: "Roadtrip! Croatia + Albania — I chat with my travel friend Cristal Dyer to reminisce about our trip, talk about what we enjoyed the most, and also what we’d do differently next time.", date: "6/12/2019", episode_url: 'https://open.spotify.com/episode/4KFSJjWPQjhA021mLAkpK6')
Episode.create(name: "Postcard Academy Travel Podcast", episode_number: 54, episode_title: "Exploring Mexico City with the World Wanderers", description: "Amanda Kingsmith and Ryan Ferguson are a Canadian couple who travel full time, but they do it slowly, often staying in one place for weeks or months at a time. Over the last year, they fell in love with Mexico City and its incredible food and culture scene. Did you know that Mexico City has more than 40,000 restaurants and the second-highest number of museums after Paris? Amanda and Ryan talk about their location independent life and all their best travel recommendations for Mexico City.", date: "5/24/2019", episode_url: 'https://open.spotify.com/episode/5Ep7aE7ZgDLgAO7Tl2MWDY')
#COMEDY
Episode.create(name: "Bertcast's Podcast", episode_number: 431, episode_title: "Rob Schneider & ME", description: "Today I talk to Actor/Comedian Rob Schneider. We talk about the making of Deuce Bigalow, what every comedian can learn from Adam Sandler, Big Daddy ad libs, Chris Rock, David Spade, SNL, and much more!", date: "9/23/2020", episode_url: 'https://open.spotify.com/episode/77hoFolVU5C5xLtLIY6s8Z')
Episode.create(name: "Bertcast's Podcast", episode_number: 397, episode_title: "Adam Richman & ME", description: "Today I chat remotely with Adam Richman from Man vs Food. We talk about working for the Travel Channel, Diplo, my Adam Sandler interview, the best places to eat, and much more! My Brand new stand up special Hey Big Boy is streaming right now on Netflix!", date: "4/9/2020", episode_url: 'https://open.spotify.com/episode/0heVG6t9ZvVnfS21tKQAgD')
Episode.create(name: "Bertcast's Podcast", episode_number: 362, episode_title: "Andrew Schulz & ME", description: "Today I sit down in the mancave with Andrew Schulz to talk about his crowd work special, guy code, surfing, Charlamagne, what animals need to go, and much more!", date: "9/4/2019", episode_url: 'https://open.spotify.com/episode/7jQzTEqJVjh1Pkqujvr6VD')
Episode.create(name: "Oh, Hello: the P'dcast", episode_number: 2, episode_title: "Boy For Sale", description: "Oh, Hello: the P'dcast has no sponsor. Instead, we’re asking listeners to join Nick Kroll and John Mulaney in donating to United Way of New York's Covid-19 Community Fund. Right now, United Way is helping get food, internet access and school supplies to New Yorkers who need it. Visit unitedway.org/ohhello to donate.", date: "4/24/2020", episode_url: 'https://open.spotify.com/episode/75ibSSr9b1rH5b4tE02SMY')
Episode.create(name: "Oh, Hello: the P'dcast", episode_number: 3, episode_title: "It's A Fine Life", description: "Oh, Hello: the P'dcast has no sponsor. Instead, we’re asking listeners to join Nick Kroll and John Mulaney in donating to Off Their Plate. Right now, Off Their Plate pays restaurants in 9 different US cities to cook free meals for hospitals and other emergency health care workers. More on what they’re doing and how to donate at bit.ly/ohhellootp.", date: "5/9/2020", episode_url: 'https://open.spotify.com/show/0siSAHSBG3cwyvncLOwobf')
Episode.create(name: "Oh, Hello: the P'dcast", episode_number: 6, episode_title: "Food, Glorious Food", description: "Oh, Hello: the P'dcast has no sponsor. Instead, we’re asking listeners to join Nick Kroll and John Mulaney in donating to Off Their Plate. Right now, Off Their Plate pays restaurants in 9 different US cities to cook free meals for hospitals and other emergency health care workers. More on what they’re doing and how to donate at bit.ly/ohhellootp.", date: "5/15/2020", episode_url: 'https://open.spotify.com/episode/6glIuPgLZeRlsOb8ars19C')
#NEWS & POLITICS
Episode.create(name: "The NPR Politics Podcast", episode_number: 400, episode_title: "Rail Force One: Biden Leads Whistle-Stop Tour After Debate", description: "The Biden campaign chartered an Amtrak train to take the president through Ohio and Pennsylvania after the first presidential debate. And, voters react to the chaos of last night's event.This episode: White House reporter Ayesha Rascoe, campaign correspondent Scott Detrow, and national political correspondent Mara Liasson.", date: "9/30/2020", episode_url: 'https://open.spotify.com/episode/1F3mIrHLGAn1L2VM0oTHgB')
Episode.create(name: "The NPR Politics Podcast", episode_number: 390, episode_title: "Weekly Roundup: September 18th", description: "A steady presidential race remains steady: Joe Biden's lead is in the high single-digits nationally. But Trump's messaging tying Joe Biden to socialism is finding purchase with Latino voters in Florida, a state that is essential to the president's re-election effort.", date: "9/18/2020", episode_url: 'https://open.spotify.com/episode/1CM6eRLc8rFncsSkPnoQlJ')
Episode.create(name: "The NPR Politics Podcast", episode_number: 300, episode_title: "Is It Safe For Kids To Return To School?", description: "The President is insistent: kids must return to school in the fall. But its not his decision to make and school districts are struggling to figure out how to open safely. Also, the Supreme Court allows more exceptions to contraception coverage. The last day of the Court's term is tomorrow.", date: "7/8/2020", episode_url: 'https://open.spotify.com/episode/3jKB4CwlTa4DhYRD1KdYLa')
Episode.create(name: "WSJ What’s News", episode_number: 425, episode_title: "Jobless Numbers Released Today as Airlines Announce Major Cuts", description: "Jobless claims are expected to remain high. South Korea's success in containing Covid-19 offers potential lessons for America. Plus, how companies are offering travel perks to help workers feel safe returning to offices.", date: "10/1/2020", episode_url: 'https://open.spotify.com/episode/7MS6NOQaacRZr1UvriF30G')
Episode.create(name: "WSJ What’s News", episode_number: 419, episode_title: "More Covid-19 Vaccines In Final Testing, Questions on Timeline Remain", description: "Johnson & Johnson is the fourth U.S. pharmaceutical company to advance to late-stage testing of a COVID-19 vaccine. But a lot of questions remain, including the timeline of when a vaccine will become widely available.", date: "9/23/2020", episode_url: 'https://open.spotify.com/episode/7I8o6l1IjWiLTzlTi6Hoom')
Episode.create(name: "WSJ What’s News", episode_number: 405, episode_title: "Postal Delays Factor Into Congressional Races", description: "Concerns over delays in mail delivery are playing out in tight Congressional races. Congressional reporter Natalie Andrews joins host Annmarie Fertoli with more details.", date: "9/3/2020", episode_url: 'https://open.spotify.com/episode/5aYI6q0puxTIyXXvrayvXt')
#MUSIC 
Episode.create(name: "Rolling Stone Music Now", episode_number: 35, episode_title: "500 Greatest Albums of All Time - Inside the List", description: "We break down what's new on Rolling Stone's rebooted list of the greatest albums ever, with Brittany Spanos, Jon Dolan, and Rob Sheffield joining host Brian Hiatt.", date: "9/29/2020", episode_url: 'https://open.spotify.com/episode/59zhDCB4NCf4ggspEoNJZD')
Episode.create(name: "Rolling Stone Music Now", episode_number: 30, episode_title: "Katy Perry and the Future of Pop", description: "Katy Perry talks with Brittany Spanos about her new album Smile, her hopes for the rest of her career and more. Plus: We break down Perry’s place in the pop universe.", date: "8/31/2020", episode_url: 'https://open.spotify.com/episode/5LCqdKAfGK1T03zeRoKZwo')
Episode.create(name: "Rolling Stone Music Now", episode_number: 27, episode_title: "The Magic of BTS - and the History of Boy Bands", description: "We look at the triumph of BTS, and how they fit in with the long history of boy bands, with Jezebel senior writer Maria Sherman (author of an upcoming boy-band history) joining Brittany Spanos, Rob Sheffield and host Brian Hiatt.", date: "3/11/2020", episode_url: 'https://open.spotify.com/episode/2garBkd1fM9knwNQ3BOtU4')
Episode.create(name: "Record Breakers Music Podcast", episode_number: 17, episode_title: "Grateful Dead's American Beauty", description: "This week, Matt finally brings his most destines pick in the legendarily harmonious jam band Grateful Dead. The gang discusses their classic 1970 release American Beauty. What did the guys think of their substance-free experience with the Dead? Hit play and find out!", date: "8/4/2020", episode_url: 'https://open.spotify.com/episode/19EbDJ5uBqo71FGs25itwi')
Episode.create(name: "Record Breakers Music Podcast", episode_number: 13, episode_title: "Vanilla Fudge's Vanilla Fudge", description: "This week, Matt brings us on a far-out psychedelic journey with Vanilla Fudge and their 1967 self-titled debut. What did the crew think of these slowed-down renditions of the hits of the time? Hit play and find out!", date: "4/29/2020", episode_url: 'https://open.spotify.com/episode/4V9tLRsvz70rlVkXRlTEfI')
Episode.create(name: "Record Breakers Music Podcast", episode_number: 4, episode_title: "Ramones' Rocket To Russia", description: "This week, Drew brings the crew one of the quintessential all-time punk rock legends in the Ramones. The gang discusses their 1977 classic “Rocket To Russia”. What did the guys think of this epic punk cornerstone? Hit play and find out!", date: "11/7/2019", episode_url: 'https://open.spotify.com/episode/2C1qllH7s1gR3wOwm6hrS1')






